name: astrokit
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  another_flushbar: ^1.10.24
  flutter_launcher_icons: ^0.9.2
  crypto: ^3.0.1
  flutter_login: ^2.2.1
  flutter_secure_storage: ^4.2.1
  http: ^0.13.4
  intl: ^0.17.0
  path_provider: ^2.0.5
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.1
  uuid: ^3.0.5

flutter_icons:
  ios: true
  android: true
  image_path: assets/launcher_icons/launch_icon.png
  adaptative_icon_background: #ffffff
  adaptative_icon_foreground: assets/launcher_icons/foreground.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
