name: astrokit
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  another_flushbar:
  flutter_launcher_icons:
  crypto:
  flutter_login:
  flutter_secure_storage:
  http:
  intl:
  path_provider:
  flutter_google_places:
  geocoding:
  uuid:
  location:
  geolocator:
  page_transition:
  json_serializable:
  build_runner:
  json_annotation:
  shared_preferences:
  provider:

flutter_icons:
  ios: true
  android: true
  image_path: assets/launcher_icons/launch_icon.png
  adaptative_icon_background: #ffffff
  adaptative_icon_foreground: assets/launcher_icons/foreground.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/images/astres/
    - assets/astres.json
