name: astrokit
description: The perfect tool for astronomy

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.1.0
  another_flushbar: ^1.10.26
  flutter_launcher_icons: ^0.9.2
  crypto: ^3.0.1
  flutter_login: ^3.0.0
  flutter_secure_storage: ^5.0.2
  http: ^0.13.4
  intl: ^0.17.0
  path_provider: ^2.0.7
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.1
  uuid: ^3.0.5
  geolocator: ^8.0.0
  page_transition: ^2.0.4
  json_serializable: ^6.1.1
  build_runner: ^2.1.5
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.9
  provider: ^6.0.1
  audioplayers: ^0.20.1
  flutter_spinkit: ^5.1.0
  video_player: 
    

flutter_icons:
  ios: true
  android: true
  image_path: assets/launcher_icons/launch_icon.png
  adaptative_icon_background: #ffffff
  adaptative_icon_foreground: assets/launcher_icons/foreground.png
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/images/astres/
    - assets/images/lmode.png
    - assets/images/nmode.png
    - assets/astres.json
    - assets/switch.mp3
    - assets/refresh.mp3
